FROM gcc:latest

RUN apt-get update && apt-get install -y libpqxx-dev libboost-dev cmake inotify-tools

WORKDIR /app

COPY crow-v1.0+5.deb .

RUN dpkg -i crow-v1.0+5.deb

COPY . .

RUN cd libbcrypt && \
	mkdir build && \ 
	cd build && \ 
	cmake .. && \
    make && \
    make install && \
    ldconfig


RUN chmod 777 hot-reload.sh

CMD ["./hot-reload.sh"]
