FROM gcc:latest

RUN apt-get update && apt-get install -y libpqxx-dev libboost-dev cmake inotify-tools git 

WORKDIR /app

COPY . .

RUN	cd test && \ 
	git submodule add https://github.com/nlohmann/json.git extern/json && \ 
	git submodule add https://github.com/google/googletest.git extern/googletest &&\ 
	git submodule add https://github.com/whoshuu/cpr.git extern/cpr && \
	ldconfig

RUN chmod 777 hot-reload.sh

CMD ["./hot-reload.sh", "./test", "./test/"]
