FROM gcc:latest

RUN apt-get update && apt-get install -y  cmake inotify-tools git 

WORKDIR /app

COPY . .

RUN	cd test_setup && \ 
	git submodule add https://github.com/google/googletest.git extern/googletest &&\ 
	git submodule add https://github.com/whoshuu/cpr.git extern/cpr && \
	ldconfig


RUN chmod 777 hot-reload-test.sh

CMD ["./hot-reload-test.sh"]
